package main

import (
	"fmt"
	"net/http"

	// docs is generated by Swag CLI, you have to import it.
	_ "github.com/Le0nar/bestiary/docs"
	"github.com/Le0nar/bestiary/internal/handler"
	"github.com/Le0nar/bestiary/internal/repository"
	"github.com/Le0nar/bestiary/internal/service"
	_ "github.com/lib/pq"
	"github.com/sirupsen/logrus"
)

const PORT = 3000

// @title Swagger Bestiary API
// @version 1.0
// @description This is a sample server.
func main() {
	db, err := repository.NewPostgresDB(repository.DatabaseConfig{
		Host:     "localhost",
		Port:     "5436",
		Username: "postgres",
		Password: "qwerty",
		DBName:   "postgres",
		SSLMode:  "disable",
	})
	if err != nil {
		logrus.Fatalf("failed to initialize db: %s", err.Error())
	}

	
	repo := repository.NewRepository(db)
	service := service.NewService(repo)
	handler := handler.NewHandler(service)

	router := handler.InitRouter(PORT)
	http.ListenAndServe(fmt.Sprintf(":%d", PORT), router)
}